### PR TITLE
Fixed persistence of simple tab when switching from Advanced to Simple

### LINKED ISSUE #35: Settings are no longer persisted when toggling from Simple to Advanced
## How to reproduce
- Go to https://jupyter-slurm.esrf.fr/hub/spawn
- Change some settings in the Simple Tab
- Launch a job
- Relinquish the job
- Go back to https://jupyter-slurm.esrf.fr/hub/spawn → _The settings were persisted thanks to #27_
- Go to the Advanced tab
- Go back to the Simple tab → **Settings are back to default !**

### PR DESCRIPTION
**Pull request by t20100**
This PR restored persisted config when switching back from advanced to simple tab and the saved config was a simple one.
The storage of the config is still done when the form is submitted and not when switching from simple to advanced tab.

Not sure what to do.
On one side I like the idea of saving the last effectively used config.
On the other hand, this can be a bit miss-leading: one can expect to come back to the simple tab with what was there the last time he show the tab content (which is possible by registering a listener on `advanced_tab_link`).

closes #35

### CODE REVIEW

File: jupyterhub_moss/form/option_form.js [hunk 1]
```diff
@@ -210,7 +210,14 @@ document.addEventListener("DOMContentLoaded", () => {
 
   // Reset when returning to simple tab
   document.getElementById('simple_tab_link').addEventListener(
-    'click', resetSpawnForm
```
Comment (loichuder) [inline jupyterhub_moss/form/option_form.js:213]: Why not simply removing this listener and let the HTML form keep its state in memory ?

Comment (t20100) [reply jupyterhub_moss/form/option_form.js:213]: Because what is read by the server are the advanced tab fields.
The simple tab fields update the advanced tab ones, so you really want things to be sync, thus the reset when switching back from advanced to simple.

Comment (loichuder) [reply jupyterhub_moss/form/option_form.js:213]: Hm, I see. We should perhaps rethink completely the handling of the form state.

**Review by loichuder — APPROVED** [review]
This will do !

File: jupyterhub_moss/form/option_form.js (hunk 1 above)
Comment (t20100) [reply jupyterhub_moss/form/option_form.js:213]: Yes, I agree, this is hackish.
